# ZAPPR default system configuration.
# All values can be overriden via commandline arguments
# or environment variables using the nconf module.

# IMPORTANT! Override secret with a secure value.
SESSION_SECRET: secret

# Override Github client id and secret with your
# own values as defined in your Github account.
GITHUB_CLIENT_ID: id
GITHUB_CLIENT_SECRET: secret
GITHUB_HOOK_SECRET: captainHook
GITHUB_SCOPES:
  - user:email
  - public_repo
  - admin:repo_hook
# See https://developer.github.com/v3/enterprise
# for GitHub Enterprise configuration.
GITHUB_UI_URL: https://github.com
GITHUB_API_URL: https://api.github.com

# Address of the web application host
# that ZAPPR is going to run on.
HOST_ADDR: http://127.0.0.1:8080
APP_PORT: 3000
METRICS_PORT: 3003
METRICS_ENABLED: true
NODE_ENV: development
STATIC_DIR: ./dist/client

# Database configuration
# sqlite or postgres
DB_DRIVER: sqlite
#DB_NAME: postgres
#DB_USER: postgres
#DB_PASS: postgres
#DB_HOST: 192.168.99.100
#DB_PORT: 5432
#DB_SCHEMA: zappr
SQLITE_FILE: ./zappr.sqlite

# Token encryption
# Options: [~, kms]
ENCRYPTION_ENGINE: ~
# ENCRYPTION_KEY: [aws kms arn]
# KMS_REGION: eu-west-1

# HTTP logging
MORGAN_FORMAT: dev
MORGAN_THRESH: 0

# Logging level
LOG_LEVEL: debug

# Zappr application configuration: opensource

AUDIT_RELEVANT_ORGS:
  - zalando
  - zalando-zmon
  - zalando-stups
  - zalando-incubator

# path to zapprfile in repository
VALID_ZAPPR_FILE_PATHS:
  - "/.zappr.yaml"
  - "/.zappr.yml"
VALID_PR_TEMPLATE_PATHS:
  - "/.github/PULL_REQUEST_TEMPLATE"
  - "/.github/PULL_REQUEST_TEMPLATE.md"
  - "/.github/PULL_REQUEST_TEMPLATE.txt"
  - "/PULL_REQUEST_TEMPLATE"
  - "/PULL_REQUEST_TEMPLATE.txt"
  - "/PULL_REQUEST_TEMPLATE.md"
ZAPPR_DEFAULT_CONFIG:
  autobranch:
    pattern: "{number}-{title}"
    length: 60
  commit:
    message:
      patterns:
        - "^#[0-9]+"
  approvals:
    minimum: 2
    ignore: none
    pattern: "^(:\\+1:|👍)$"
    veto:
      # veto/blocking a PR = comment that matches this regex
      pattern: "^(:\\-1:|👎)$"
  specification:
    title:
      minimum-length:
        enabled: true
        length: 8
    body:
      minimum-length:
        enabled: true
        length: 8
      contains-url: true
      contains-issue-number: true
    template:
      differs-from-body: true
